#!/bin/sh
# Setup a machine for Sublime Text 3
# set -x # shows executed commands

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/
mv "$sublime_dir/Packages" "$sublime_dir/Packages.backup"
ln -s "$ZSH/sublime3/Packages" "$sublime_dir"
ln -s "/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl" "$ZSH/bin/subl"
